In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sqlalchemy import create_engine

In [2]:
engine = create_engine('mysql+pymysql://root:Admin%40123@localhost/amazon_ads_db')
query = "SELECT * FROM bid_optimization_metrics"
master_df = pd.read_sql(query, con=engine)

In [3]:
master_df

,date,campaign_id,product_id,is_weekend,is_salary_day,daily_budget,current_bid,organic_rank,competitor_pressure,clicks,...,optimal_bid,sales_lag_1,acos_lag_1,spend_lag_1,bid_budget_ratio,roas_lag_1,ad_intensity_index,avg_cvr_7d,avg_acos_7d,spend_velocity
0,2023-02-13,6c788904-66fb-4701-9a90-349d6c66c447,a9d07467-76cd-4dbc-b245-f003297b5b32,0,0,2277.251916,2.03,42,1.30,784,...,1.83,0.00,0.00,0.00,0.000891,0.00,54.60,0.000000,0.000000,0.000000
1,2023-02-14,6c788904-66fb-4701-9a90-349d6c66c447,f6b9f302-0352-45cb-bd0d-6c74f2466b9f,0,0,2632.841034,4.62,11,1.22,376,...,4.16,560.42,368.42,2064.70,0.001755,0.27,13.42,0.000000,0.000000,0.784210
2,2023-02-15,6c788904-66fb-4701-9a90-349d6c66c447,b6bcc51c-940f-4700-b7cd-7de524573575,0,0,2496.014420,3.68,40,0.89,676,...,3.31,952.36,223.35,2127.08,0.001474,0.45,35.60,0.000000,0.000000,0.852191
3,2023-02-16,6c788904-66fb-4701-9a90-349d6c66c447,439b9b4b-dfe9-4570-9e07-e734b6538680,0,0,2417.168342,2.89,36,1.32,554,...,2.60,867.66,255.49,2216.77,0.001196,0.39,47.52,0.000000,0.000000,0.917094
4,2023-02-17,6c788904-66fb-4701-9a90-349d6c66c447,51234636-ab69-4a66-9ca5-b29fd9cc3611,0,0,2031.756725,1.70,14,1.46,655,...,1.53,746.20,283.11,2112.60,0.000837,0.35,20.44,0.000000,0.000000,1.039790
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5470,2026-02-07,d38c1acb-a4b8-49a1-8c62-9867a812f5f6,303422ee-04ae-4640-99e7-b0cefd7e05d2,1,0,2142.494253,1.91,31,0.98,970,...,1.72,957.15,240.50,2301.99,0.000891,0.42,30.38,0.000486,194.217143,1.074444
5471,2026-02-08,d38c1acb-a4b8-49a1-8c62-9867a812f5f6,a9d07467-76cd-4dbc-b245-f003297b5b32,1,0,1487.560387,3.84,43,0.69,467,...,3.46,1540.40,117.43,1808.91,0.002581,0.85,29.67,0.000443,201.991429,1.216025
5472,2026-02-09,d38c1acb-a4b8-49a1-8c62-9867a812f5f6,f4fa8d96-bbac-481e-9053-c5eab18a3af3,0,0,2210.276991,2.99,16,0.64,937,...,2.69,1468.02,83.95,1232.43,0.001353,1.19,10.24,0.000443,198.908571,0.557591
5473,2026-02-10,d38c1acb-a4b8-49a1-8c62-9867a812f5f6,0d8d2eff-f6a6-4826-b4fe-cfe5e3636df4,0,0,1527.134320,1.74,47,0.78,956,...,1.57,701.66,257.29,1805.28,0.001139,0.39,36.66,0.000600,192.561429,1.182136
5474,2026-02-11,d38c1acb-a4b8-49a1-8c62-9867a812f5f6,a98afbbb-23af-436f-8d58-378aec770f09,0,0,2898.875881,5.37,49,1.13,393,...,4.83,370.33,349.23,1293.32,0.001852,0.29,55.37,0.000600,215.014286,0.446145

In [4]:
master_df.describe()

,is_weekend,is_salary_day,daily_budget,current_bid,organic_rank,competitor_pressure,clicks,spend,sales,orders,...,optimal_bid,sales_lag_1,acos_lag_1,spend_lag_1,bid_budget_ratio,roas_lag_1,ad_intensity_index,avg_cvr_7d,avg_acos_7d,spend_velocity
count,5475.000000,5475.000000,5475.000000,5475.000000,5475.000000,5475.000000,5475.000000,5475.000000,5475.000000,5475.000000,...,5475.000000,5475.000000,5475.000000,5475.000000,5475.000000,5475.000000,5475.000000,5475.000000,5475.000000,5475.000000
mean,0.284932,0.376256,1897.932104,3.502150,25.083836,1.004292,588.191963,1662.101512,1056.009005,0.603653,...,3.152042,1055.331711,205.267854,1660.447640,0.002105,0.636121,25.226130,0.001303,203.964168,0.998487
std,0.451423,0.484490,635.460107,1.157378,14.202722,0.288932,376.340373,563.175889,753.908240,1.079074,...,1.041698,754.458587,91.472618,565.069703,0.001107,0.381850,16.558809,0.000936,32.281719,0.538068
min,0.000000,0.000000,800.046023,1.500000,1.000000,0.500000,89.000000,646.650000,178.320000,0.000000,...,1.350000,0.000000,0.000000,0.000000,0.000509,0.000000,0.500000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,1345.935376,2.490000,13.000000,0.750000,324.500000,1178.625000,544.270000,0.000000,...,2.240000,543.885000,118.535000,1177.255000,0.001286,0.380000,11.510000,0.000614,184.027143,0.616773
50%,0.000000,0.000000,1886.186295,3.490000,25.000000,1.000000,489.000000,1653.210000,818.870000,0.000000,...,3.140000,818.490000,213.350000,1651.610000,0.001852,0.470000,23.100000,0.001129,205.512857,0.869993
75%,1.000000,1.000000,2448.572588,4.530000,37.000000,1.260000,752.000000,2132.895000,1266.760000,1.000000,...,4.080000,1266.760000,264.450000,2131.485000,0.002632,0.840000,36.530000,0.001786,225.007143,1.240741
max,1.000000,1.000000,2999.528632,5.500000,49.000000,1.500000,3132.000000,2821.510000,5029.630000,8.000000,...,4.950000,5029.630000,484.350000,2821.510000,0.006660,1.990000,73.500000,0.006457,296.280000,3.321938

In [5]:
master_df.columns

Index(['date', 'campaign_id', 'product_id', 'is_weekend', 'is_salary_day',
       'daily_budget', 'current_bid', 'organic_rank', 'competitor_pressure',
       'clicks', 'spend', 'sales', 'orders', 'cvr', 'acos', 'optimal_bid',
       'sales_lag_1', 'acos_lag_1', 'spend_lag_1', 'bid_budget_ratio',
       'roas_lag_1', 'ad_intensity_index', 'avg_cvr_7d', 'avg_acos_7d',
       'spend_velocity'],
      dtype='object')

In [6]:
master_df['sales_lag_1'] = master_df['sales'].shift(1)

master_df['avg_sales_7d'] = (
    master_df['sales']
    .rolling(window=7)
    .mean()
    .shift(1)
)

In [7]:
master_df['sales_lag_1'] = master_df.groupby('campaign_id')['sales'].shift(1)

In [8]:
master_df.drop(['campaign_id','product_id','clicks','spend','sales','orders','cvr','acos','spend_velocity'],axis=1,inplace=True)

In [9]:
master_df.columns

Index(['date', 'is_weekend', 'is_salary_day', 'daily_budget', 'current_bid',
       'organic_rank', 'competitor_pressure', 'optimal_bid', 'sales_lag_1',
       'acos_lag_1', 'spend_lag_1', 'bid_budget_ratio', 'roas_lag_1',
       'ad_intensity_index', 'avg_cvr_7d', 'avg_acos_7d', 'avg_sales_7d'],
      dtype='object')

In [10]:
master_df

,date,is_weekend,is_salary_day,daily_budget,current_bid,organic_rank,competitor_pressure,optimal_bid,sales_lag_1,acos_lag_1,spend_lag_1,bid_budget_ratio,roas_lag_1,ad_intensity_index,avg_cvr_7d,avg_acos_7d,avg_sales_7d
0,2023-02-13,0,0,2277.251916,2.03,42,1.30,1.83,NaN,0.00,0.00,0.000891,0.00,54.60,0.000000,0.000000,NaN
1,2023-02-14,0,0,2632.841034,4.62,11,1.22,4.16,560.42,368.42,2064.70,0.001755,0.27,13.42,0.000000,0.000000,NaN
2,2023-02-15,0,0,2496.014420,3.68,40,0.89,3.31,952.36,223.35,2127.08,0.001474,0.45,35.60,0.000000,0.000000,NaN
3,2023-02-16,0,0,2417.168342,2.89,36,1.32,2.60,867.66,255.49,2216.77,0.001196,0.39,47.52,0.000000,0.000000,NaN
4,2023-02-17,0,0,2031.756725,1.70,14,1.46,1.53,746.20,283.11,2112.60,0.000837,0.35,20.44,0.000000,0.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5470,2026-02-07,1,0,2142.494253,1.91,31,0.98,1.72,957.15,240.50,2301.99,0.000891,0.42,30.38,0.000486,194.217143,1343.510000
5471,2026-02-08,1,0,1487.560387,3.84,43,0.69,3.46,1540.40,117.43,1808.91,0.002581,0.85,29.67,0.000443,201.991429,1182.232857
5472,2026-02-09,0,0,2210.276991,2.99,16,0.64,2.69,1468.02,83.95,1232.43,0.001353,1.19,10.24,0.000443,198.908571,1065.534286
5473,2026-02-10,0,0,1527.134320,1.74,47,0.78,1.57,701.66,257.29,1805.28,0.001139,0.39,36.66,0.000600,192.561429,1049.667143
5474,2026-02-11,0,0,2898.875881,5.37,49,1.13,4.83,370.33,349.23,1293.32,0.001852,0.29,55.37,0.000600,215.014286,958.751429