In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sqlalchemy import create_engine

In [4]:
engine = create_engine('mysql+pymysql://root:Admin%40123@localhost/amazon_ads_db')
query = "SELECT * FROM bid_optimization_metrics"
master_df = pd.read_sql(query, con=engine)

In [5]:
master_df

,date,campaign_id,product_id,is_weekend,is_salary_day,daily_budget,current_bid,organic_rank,competitor_pressure,clicks,spend,sales,orders,cvr,acos,optimal_bid,avg_cvr_7d,spend_velocity
0,2023-02-12,0a7bb15b-389c-4b9b-8024-70433e999f68,9e3013ec-96ce-4eb7-8fa8-3f8d334ed562,1,0,1594.454232,1.93,46,1.09,683,1437.67,1097.36,2,0.0029,131.01,1.74,0.000000,0.901669
1,2023-02-13,0a7bb15b-389c-4b9b-8024-70433e999f68,5ee8e358-3bac-49aa-9740-afded14f7620,0,0,2400.136971,4.30,7,0.92,563,2227.83,899.51,0,0.0000,247.67,3.87,0.000000,0.928210
2,2023-02-14,0a7bb15b-389c-4b9b-8024-70433e999f68,5ee8e358-3bac-49aa-9740-afded14f7620,0,0,2742.476174,3.93,32,0.56,1021,2235.32,1038.78,0,0.0000,215.19,3.54,0.000000,0.815074
3,2023-02-15,0a7bb15b-389c-4b9b-8024-70433e999f68,a4641943-2ad7-431e-ba44-e15249bc80f8,0,0,1071.873318,5.41,27,0.98,166,886.51,511.62,1,0.0060,173.28,4.87,0.000000,0.827066
4,2023-02-16,0a7bb15b-389c-4b9b-8024-70433e999f68,cd0e30c1-6fac-4573-8278-397cdd7c1d64,0,0,2835.490062,4.83,23,0.70,751,2522.57,1135.14,2,0.0027,222.23,4.35,0.000000,0.889642
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5470,2026-02-06,6d232bc4-f13b-4574-ac8b-70cbdf95de3a,acfe33d1-481d-454e-b650-f80033503879,0,0,1195.287327,4.24,39,1.25,196,1036.96,467.11,0,0.0000,221.99,3.82,0.000429,0.867540
5471,2026-02-07,6d232bc4-f13b-4574-ac8b-70cbdf95de3a,182ca235-fc26-4860-8d8c-390d37a4bc2e,1,0,1757.868407,4.32,16,1.33,277,1597.19,1796.43,1,0.0036,88.91,3.89,0.000429,0.908595
5472,2026-02-08,6d232bc4-f13b-4574-ac8b-70cbdf95de3a,1c03f8d4-871c-41f4-8b16-73e5e1fde85b,1,0,1995.449558,5.02,43,1.37,257,1776.82,2340.52,1,0.0039,75.92,4.52,0.000786,0.890436
5473,2026-02-09,6d232bc4-f13b-4574-ac8b-70cbdf95de3a,227aa61c-1fb9-4ee1-b98f-fd57a8243eff,0,0,1532.514268,5.19,18,0.69,390,1389.55,620.04,1,0.0026,224.11,4.67,0.001229,0.906713
5474,2026-02-10,6d232bc4-f13b-4574-ac8b-70cbdf95de3a,3c51f577-e687-42a6-8079-e4a3e81afa2e,0,0,2064.193647,2.77,46,1.22,510,1719.61,561.18,0,0.0000,306.43,2.49,0.001600,0.833066

In [6]:
master_df.describe()

,is_weekend,is_salary_day,daily_budget,current_bid,organic_rank,competitor_pressure,clicks,spend,sales,orders,cvr,acos,optimal_bid,avg_cvr_7d,spend_velocity
count,5475.000000,5475.000000,5475.000000,5475.000000,5475.000000,5475.000000,5475.000000,5475.000000,5475.000000,5475.000000,5475.000000,5475.000000,5475.000000,5475.000000,5475.000000
mean,0.285845,0.376256,1894.546137,3.533876,25.060274,1.004353,581.403288,1655.428983,1061.244818,0.588858,0.001255,203.955140,3.180647,0.001247,0.873903
std,0.451857,0.484490,634.863022,1.165250,14.175502,0.286789,370.247982,560.328370,758.498533,1.070029,0.002488,90.444966,1.048761,0.000837,0.042759
min,0.000000,0.000000,800.051842,1.500000,1.000000,0.500000,95.000000,653.110000,159.090000,0.000000,0.000000,50.630000,1.350000,0.000000,0.800004
25%,0.000000,0.000000,1341.102024,2.510000,13.000000,0.750000,320.000000,1166.510000,541.355000,0.000000,0.000000,117.385000,2.260000,0.000614,0.837166
50%,0.000000,0.000000,1879.002486,3.550000,25.000000,1.010000,483.000000,1642.090000,823.440000,0.000000,0.000000,211.490000,3.190000,0.001100,0.872959
75%,1.000000,1.000000,2439.183318,4.560000,37.000000,1.250000,743.000000,2122.630000,1264.905000,1.000000,0.001700,262.730000,4.100000,0.001686,0.910620
max,1.000000,1.000000,2999.018591,5.500000,49.000000,1.500000,3119.000000,2844.730000,4756.060000,8.000000,0.021900,495.040000,4.950000,0.006071,0.949936

In [7]:
master_df.columns

Index(['date', 'campaign_id', 'product_id', 'is_weekend', 'is_salary_day',
       'daily_budget', 'current_bid', 'organic_rank', 'competitor_pressure',
       'clicks', 'spend', 'sales', 'orders', 'cvr', 'acos', 'optimal_bid',
       'avg_cvr_7d', 'spend_velocity'],
      dtype='object')

In [8]:
master_df.drop(['campaign_id','product_id','clicks','spend','sales','orders','cvr','acos','spend_velocity'],axis=1,inplace=True)

In [9]:
master_df.columns

Index(['date', 'is_weekend', 'is_salary_day', 'daily_budget', 'current_bid',
       'organic_rank', 'competitor_pressure', 'optimal_bid', 'avg_cvr_7d'],
      dtype='object')